<?php
/**
 * Table Definition for AGLOA2017playerImport
 */
require_once 'DB/DataObject.php';

class AGLOA2017playerImport extends DB_DataObject 
{
    ###START_AUTOCODE
    /* the code below is auto generated do not remove the above tag */

    public $__table = 'AGLOA2017playerImport';    // table name
    public $ID;                             // int(4)
    public $LAST;                           // varchar(16)
    public $FIRST;                          // varchar(12)
    public $DIVISION;                       // varchar(1)
    public $GEOCODE;                        // varchar(2)
    public $W1;                             // varchar(3)
    public $W2;                             // varchar(3)
    public $W3;                             // varchar(3)
    public $W4;                             // varchar(3)
    public $IW1;                            // varchar(10)
    public $IW2;                            // varchar(10)
    public $IW3;                            // varchar(10)
    public $TW1;                            // varchar(3)
    public $TW2;                            // varchar(10)
    public $TW3;                            // varchar(10)
    public $WTOTAL;                         // varchar(4)
    public $E1;                             // varchar(3)
    public $E2;                             // varchar(3)
    public $E3;                             // varchar(3)
    public $E4;                             // varchar(3)
    public $IE1;                            // varchar(3)
    public $IE2;                            // varchar(3)
    public $IE3;                            // varchar(3)
    public $TE1;                            // varchar(3)
    public $TE2;                            // varchar(3)
    public $TE3;                            // varchar(10)
    public $ETOTAL;                         // varchar(4)
    public $O1;                             // varchar(3)
    public $O2;                             // varchar(3)
    public $O3;                             // varchar(3)
    public $O4;                             // varchar(3)
    public $IO1;                            // varchar(3)
    public $IO2;                            // varchar(3)
    public $IO3;                            // varchar(3)
    public $TO1;                            // varchar(3)
    public $TO2;                            // varchar(3)
    public $TO3;                            // varchar(10)
    public $OTOTAL;                         // varchar(4)
    public $A1;                             // varchar(4)
    public $A2;                             // varchar(5)
    public $A3;                             // varchar(4)
    public $A4;                             // varchar(5)
    public $IA1;                            // varchar(10)
    public $IA2;                            // varchar(10)
    public $IA3;                            // varchar(10)
    public $TA1;                            // varchar(10)
    public $TA2;                            // varchar(10)
    public $TA3;                            // varchar(10)
    public $ATOTAL;                         // varchar(5)
    public $M1;                             // varchar(4)
    public $M2;                             // varchar(4)
    public $M3;                             // varchar(3)
    public $M4;                             // varchar(3)
    public $IM1;                            // varchar(10)
    public $IM2;                            // varchar(10)
    public $IM3;                            // varchar(10)
    public $TM1;                            // varchar(10)
    public $TM2;                            // varchar(10)
    public $TM3;                            // varchar(10)
    public $MTOTAL;                         // varchar(5)
    public $L1;                             // varchar(3)
    public $L2;                             // varchar(3)
    public $L3;                             // varchar(3)
    public $L4;                             // varchar(3)
    public $IL1;                            // varchar(3)
    public $IL2;                            // varchar(3)
    public $IL3;                            // varchar(3)
    public $TL1;                            // varchar(3)
    public $TL2;                            // varchar(3)
    public $TL3;                            // varchar(10)
    public $LTOTAL;                         // varchar(4)
    public $P1;                             // varchar(5)
    public $P2;                             // varchar(5)
    public $P3;                             // varchar(4)
    public $P4;                             // varchar(5)
    public $IP1;                            // varchar(3)
    public $IP2;                            // varchar(10)
    public $IP3;                            // varchar(10)
    public $TP1;                            // varchar(10)
    public $TP2;                            // varchar(10)
    public $TP3;                            // varchar(10)
    public $PTOTAL;                         // varchar(5)
    public $MATHTOTAL;                      // varchar(10)
    public $LANGTOTAL;                      // varchar(10)
    public $SOCTOTAL;                       // varchar(10)
    public $SWEEPSTAKE;                     // varchar(4)
    public $PLACE;                          // varchar(10)
    public $WTEAM;                          // varchar(4)
    public $ETEAM;                          // varchar(4)
    public $OTEAM;                          // varchar(4)
    public $ATEAM;                          // varchar(4)
    public $MTEAM;                          // varchar(4)
    public $LTEAM;                          // varchar(4)
    public $PTEAM;                          // varchar(4)
    public $C1;                             // decimal(4,2)
    public $C2;                             // decimal(5,2)
    public $C3;                             // decimal(3,2)
    public $C4;                             // decimal(3,2)
    public $IC1;                            // varchar(5)
    public $IC2;                            // varchar(3)
    public $IC3;                            // varchar(3)
    public $TC1;                            // varchar(3)
    public $TC2;                            // varchar(3)
    public $TC3;                            // varchar(3)
    public $CTOTAL;                         // decimal(5,2)
    public $CTEAM;                          // varchar(4)

    /* the code above is auto generated do not remove the tag below */
    ###END_AUTOCODE
}
