<?php
// this is normally contained in your DataObjects file (autogenerated by the generator)
require_once 'DataObjects/Player.php';

// this is the common configuration code - place in a general site wide include file.

// this  the code used to load and store DataObjects Configuration.
$options = &PEAR::getStaticProperty('DB_DataObject','options');
$config = parse_ini_file('tournament.ini',TRUE);
foreach($config as $class=>$values) {
	$options = &PEAR::getStaticProperty($class,'options');
	$options = $values;
}

$player = new Player; 
// DB_DataObject Error: You cannot do run count without keys - use $do->count('id'), or use $do->count('distinct id')'; 
echo "<br/>There are {$player->count('id')} {$player->__table} records in the {$player->_database} database.";
echo "<br/>There are {$player->count('DISTINCT last_name')} {$player->__table} records with distinct last names in the {$player->_database} database.";

// Delete any existing 'Sample' tests
$player = new Player;
$player->last_name = 'Sample';
$player->delete();

// Begin testing by adding a new Sample
$player = new Player; 
$player->id ='1';
$player->last_name ='Sample';
$player->first_name ='One';
$player->birth_date = "1961-02-04";
$id = $player->insert();
var_dump($player);

// Make sure we can update
$player = new Player;
$player->first_name ='Two';
$player->whereAdd('id = 1');
$player->update(DB_DATAOBJECT_WHEREADD_ONLY); // Cannot use simple get since DB_DataObject interprets unique keys as primary

$last = 'Sample';
$player = new Player;
$player->whereAdd("last_name like '{$last}%'");
echo "<br/>There are {$player->count('id', DB_DATAOBJECT_WHEREADD_ONLY)} {$player->__table} records in the {$player->_database} database whose last names begin with {$last}.";

$player->get(1); // get the record using the primary key.
var_dump($player);

$player->get('last_name' , 'Sample');
var_dump($player);

$first = 'Two';
$player = new Player;
$player->first_name = $first;
$total = $player->count('id');
echo "There are {$total} players with a first_name like $first:";

$player->find();
while ($player->fetch())
var_dump($player);

$player = new Player;

// test raw queries
$player = new Player; 
$player->query("SELECT * FROM {$player->__table} WHERE id < 200 ORDER BY id");
while ($player->fetch()) {
	var_dump($player);
}

$player = new Player;
$player->selectAdd("DATE_FORMAT(birth_date,'%d %m %Y') as birthday_formatted ");
$player->whereAdd("birth_date IS NOT NULL");
$player->find();

while ($player->fetch()) {
  var_dump($player);
}

?>